### ISSUE TITLE
SyntaxError on load

### ISSUE THREAD

**Issue by Einlar** [linjer/jekyll-katex#6] opened 2018-09-30 12:54 UTC
I'm new to Jekyll, so maybe I'm doing something wrong. 
Anyway, I've followed steps 1 and 2 from the readme, and `bundle install` goes well (I'm running ruby 2.5.1p57 on a x64 Win 10 machine, with Jekyll 3.8.4).
But then, when I try to run with `bundle exec jekyll serve`, I get this:

```
Configuration file: C:/Users/franc/Documents/GitHub/Einlar.github.io/_config.yml
Katex Configuration: Found KaTeX js at: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/assets/js//katex.min.js
Traceback (most recent call last):
10: from C:/Ruby25-x64/bin/jekyll:23:in `<main>'
9: from C:/Ruby25-x64/bin/jekyll:23:in `load'
8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/exe/jekyll:11:in `<top (required)>'
7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:114:in `require'
5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `require'
4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `each'
3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `block in require'
2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `each'
1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll-katex'. (Bundler::GemRequireError)
Gem Load Error is: SyntaxError: Previsto identificatore
Backtrace for gem load error is:
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex/katex_js.rb:10:in `<module:Katex>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex/katex_js.rb:9:in `<module:Jekyll>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex/katex_js.rb:7:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll/tags/katex.rb:4:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll/tags/katex.rb:4:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex.rb:4:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex.rb:4:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `block in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:114:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/exe/jekyll:11:in `<top (required)>'
C:/Ruby25-x64/bin/jekyll:23:in `load'
C:/Ruby25-x64/bin/jekyll:23:in `<main>'
Bundler Error Backtrace:
```

Adding CSS and fonts as of step 3 does not change the situation. Is this a bug of the plugin or am I doing something wrong?

**Comment by linjer** [comment] 2018-10-09 14:49
@Einlar Thanks for the bug report. It looks like it's throwing an ambiguous error when compiling. Can you help me reproduce the issue? Do you know if there's a block you're trying to render that is causing the issue?

**Comment by linjer** [comment] 2018-10-09 14:51
Also, what is your config for `katex` look like?

**Comment by Einlar** [comment] 2018-10-09 15:25
I've setup Jekyll following these [commands](https://jekyllrb.com/docs/). The error appears with the standard config file (I've only added jekyll-katex to the gemfile and config). I've uploaded all the files [here](https://drive.google.com/open?id=1cqLCCwYWa5Ps5nQjTd26fcirLg3r-TSE). 
Here is the result of "bundle install" and the complete error:
```
PS C:\Users\franc\Desktop\katex_test> bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 3.0.3
Using addressable 2.5.2
Using bundler 1.16.5
Using colorator 1.1.0
Using concurrent-ruby 1.0.5
Using eventmachine 1.2.7 (x64-mingw32)
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Fetching execjs 2.7.0
Installing execjs 2.7.0
Using ffi 1.9.25 (x64-mingw32)
Using forwardable-extended 2.6.0
Using i18n 0.9.5
Using rb-fsevent 0.10.3
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.6.0
Using jekyll-sass-converter 1.5.2
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.0.0
Using kramdown 1.17.0
Using liquid 4.0.1
Using mercenary 0.3.6
Using pathutil 0.16.1
Using rouge 3.3.0
Using safe_yaml 1.0.4
Using jekyll 3.8.4
Using jekyll-feed 0.11.0
Fetching jekyll-katex 0.3.0
Installing jekyll-katex 0.3.0
Using jekyll-seo-tag 2.5.0
Using minima 2.5.0
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using tzinfo-data 1.2018.5
Using wdm 0.1.1
Bundle complete! 6 Gemfile dependencies, 35 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
PS C:\Users\franc\Desktop\katex_test> bundle exec jekyll serve
Configuration file: C:/Users/franc/Desktop/katex_test/_config.yml
Katex Configuration: Found KaTeX js at: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/assets/js//katex.min.js
Traceback (most recent call last):
        10: from C:/Ruby25-x64/bin/jekyll:23:in `<main>'
         9: from C:/Ruby25-x64/bin/jekyll:23:in `load'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/exe/jekyll:11:in `<top (required)>'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:114:in `require'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `require'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `each'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `block in require'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `each'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll-katex'. (Bundler::GemRequireError)
Gem Load Error is: SyntaxError: Expected identifier
Backtrace for gem load error is:
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex/katex_js.rb:10:in `<module:Katex>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex/katex_js.rb:9:in `<module:Jekyll>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex/katex_js.rb:7:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll/tags/katex.rb:4:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll/tags/katex.rb:4:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex.rb:4:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-katex-0.3.0/lib/jekyll-katex.rb:4:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `block in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:114:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/exe/jekyll:11:in `<top (required)>'
C:/Ruby25-x64/bin/jekyll:23:in `load'
C:/Ruby25-x64/bin/jekyll:23:in `<main>'
Bundler Error Backtrace:
PS C:\Users\franc\Desktop\katex_test>
```

**Comment by linjer** [comment] 2018-10-10 05:08
@Einlar I cannot reproduce the issue on my system, which is running on macOS High Sierra. This suggests there's probably an environment pre-req I missed.

Looking at the stacktrace more carefully, it looks like it might be due to a missing Javascript runtime? You can see the [supported list of runtimes here](https://github.com/sstephenson/execjs).

If you think this might be the issue, could you try adding `gem 'therubyracer'` to your project's `Gemfile`/`gems.rb` then trying again?

**Comment by linjer** [comment] 2018-10-12 20:43
@Einlar Assuming the javascript engine is the cause. I think I either need to add a javascript engine to the pre-requisites or include an engine (e.g., `therubyracer`). It's unclear if this is the root cause, but I might want to include an engine directly anyway.

Would love to know if you have any thoughts. Please let me know if you are able to isolate the issue further.

**Comment by linjer** [comment] 2018-10-31 16:33
@Einlar Since I cannot isolate the issue that is causing the problem for you, without more information, I'm going to close this issue and move forward with a standalone Javascript engine.

If you are still having issues or find any more interesting information, feel free to let me know! Appreciate it!

**Closed as completed by linjer** 2018-10-31 16:33 UTC
Labels: question
